spring.application.name=EPMS
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.datasource.url=jdbc:mysql://localhost:3306/epms
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect